name: Build Container

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:

    - uses: actions/checkout@v1

    - name: Build the image
      run: docker build . --file Dockerfile --tag rust-esp8266:${{ github.sha }}

    - name: Authenticate
      run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login --username ${{secrets.REGISTRY_USERNAME}} --password-stdin

    - name: Tag the image (master)
      if: github.ref == 'refs/heads/master'
      run: docker tag rust-esp8266:${{ github.sha }} eris377114/rust-esp8266:latest
    - name: Push the image (master)
      if: github.ref == 'refs/heads/master'
      run: docker push eris377114/rust-esp8266:latest
